### ISSUE TITLE
Tab Plugin 1.19 and PlaceholderAPI 2.11.3 Crash

### ISSUE THREAD

**Issue by yzz17** [SemBL06/TabPlugin#1]
the following error removes the users from the server and sends me this
https://paste.gg/p/anonymous/6f122376301e47698feb6fa26a312f9b

config: %player_ping%,  %player_name%, %server_online%, §f%animations_<marquee width=22 space=8>,

**Comment by SemBL06** [comment]
Thanks for reporting this bug. Can you provide the software and Minecraft version you are using? Btw did the first configuration work?

**Comment by yzz17** [comment]
yes first config was fine, is 1.20.1 , and i try paper server last ver, and purpur last ver, I have the theory that: getUniqueId() on a player object that is null. This means that the player object has not been initialized or assigned a value before the getUniqueId() method is called. The error occurs on line 85 of the AnimationExpansion.java file in the getAnimationsCache() method?

**Comment by yzz17** [comment]
![image](https://github.com/SemBL06/TabPlugin/assets/13352920/4462165a-cfe7-473a-b09a-d47b8808ae79)

default config is absent a % :) .. before I forget, I really like the plugin, really thanks for creating it

**Comment by SemBL06** [comment]
Thanks for your review! ♥

**Comment by yzz17** [comment]
heres my config 

https://paste.gg/p/anonymous/a8ffa8d947c64df1b9840c4b22eb873e

**Comment by SemBL06** [comment]
You made several config mistakes:
- \n\n in the header and footer is (I think) not possible. 
- \n in the beginning is not possible, you always need a first line.
- In header you have a \n in the end. This will cause issue's.
- What also might result in issue is the amount of \n in your config. A tablist isn't infintely long.
Please use the default config as a template, it is way more easier. You can customise it from there.
If you really want to make your own config, then watch out for the \n.

**Comment by SemBL06** [comment]
I hope this helps you out. If you have any other issue's let me know!

**Comment by SemBL06** [comment]
Btw I made an update for the plugin where I fixed the % (thanks to you ♥) and added the amount of time the tablist updates in the config.

**Comment by yzz17** [comment]
Thank you, I think you're right, I'll be more careful and if I find something I'll gladly share
