### ISSUE TITLE
Doesn't make new line

### ISSUE THREAD

**Issue by theflamebeast** [SemBL06/TabPlugin#2]
How do you make a new line in tagprefix? I tried \n, it doesn't work.

**Comment by SemBL06** [comment]
Did the default config work? If so, send me your conifg:)

**Comment by theflamebeast** [comment]
> Did the default config work? If so, send me your conifg:)

wdym

**Comment by theflamebeast** [comment]
oh bruh i posted this on the wrong plugin, I'm using the regular TAB plugin.
